# Generated by Django 4.2.3 on 2023-07-26 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(blank=True, max_length=200, null=True)),
                ('any_video_id', models.CharField(blank=True, max_length=200, null=True)),
                ('channel_id', models.CharField(blank=True, max_length=200, null=True)),
                ('subscibers', models.PositiveIntegerField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(blank=True, null=True)),
                ('started_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('your_description', models.TextField(blank=True, max_length=200, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('revenue_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('monetization', models.CharField(blank=True, choices=[('Adsence', 'Adsence'), ('No Monetization', 'No Monetization'), ('Affiliation', 'Affiliation')], default='No Monetization', max_length=200, null=True)),
                ('post_views', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Sold', 'Sold')], default='Pending', max_length=200, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
