# Generated by Django 4.2.3 on 2023-07-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeproduct',
            name='channel_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='youtubeproduct',
            name='channel_custom_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='youtubeproduct',
            name='thumbnail_default_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='youtubeproduct',
            name='total_video_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
