# Generated by Django 4.2.3 on 2023-07-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_youtubeproduct_channel_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='display_price',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('TZS', 'TZS'), ('KES`,', 'KES')], max_length=200),
        ),
    ]
