# Generated by Django 4.2.3 on 2023-07-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_userinfo_country_userinfo_display_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeproduct',
            name='started_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
