# Generated by Django 4.2.3 on 2023-08-01 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=200, null=True)),
                ('domain_authority', models.CharField(blank=True, max_length=200, null=True)),
                ('monthly_visitors', models.PositiveIntegerField(blank=True, null=True)),
                ('started_date', models.DateTimeField(blank=True, null=True)),
                ('website_country', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('revenue_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('monetization', models.CharField(blank=True, choices=[('Adsence', 'Adsence'), ('No Monetization', 'No Monetization'), ('Affiliation', 'Affiliation')], default='No Monetization', max_length=200, null=True)),
                ('post_views', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Sold', 'Sold')], default='Pending', max_length=200, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('account_id', models.CharField(blank=True, max_length=200, null=True)),
                ('followers', models.PositiveIntegerField(blank=True, null=True)),
                ('total_posts', models.PositiveIntegerField(blank=True, null=True)),
                ('started_date', models.DateTimeField(blank=True, null=True)),
                ('account_country', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Sold', 'Sold')], default='Pending', max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TikTokAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('account_id', models.CharField(blank=True, max_length=200, null=True)),
                ('followers', models.PositiveIntegerField(blank=True, null=True)),
                ('total_posts', models.PositiveIntegerField(blank=True, null=True)),
                ('started_date', models.DateTimeField(blank=True, null=True)),
                ('account_country', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Sold', 'Sold')], default='Pending', max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('account_id', models.CharField(blank=True, max_length=200, null=True)),
                ('followers', models.PositiveIntegerField(blank=True, null=True)),
                ('total_posts', models.PositiveIntegerField(blank=True, null=True)),
                ('started_date', models.DateTimeField(blank=True, null=True)),
                ('account_country', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Sold', 'Sold')], default='Pending', max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
